### ISSUE TITLE
Trouble running tof_test.py and plot_tof_test.py in how_to_build_and_install.md

### ISSUE THREAD

**Issue by eliaskrchnr** [YDLIDAR/YDLidar-SDK#43]
I did the installation, could start the lidar, and it seems like I get some data. When I tried to visualize the data with tof_test.py and plot_tof_test.py following the [instructions](https://github.com/YDLIDAR/YDLidar-SDK/blob/master/doc/howto/how_to_build_and_install.md), I got some errors. Since I don't know what I'm doing, I tried using `python3 tof_test.py` instead of the suggested `python tof_test.py`. Only the type of error changed, like it is seen in the picture.
I'm glad for help.
```
elias@elias-ThinkPad:~/YDLidar-SDK/python/examples$ python tof_test.py
Traceback (most recent call last):
  File "tof_test.py", line 2, in <module>
    import ydlidar
  File "/home/elias/YDLidar-SDK/python/examples/ydlidar.py", line 15, in <module>
    import _ydlidar
ImportError: dynamic module does not define init function (init_ydlidar)
elias@elias-ThinkPad:~/YDLidar-SDK/python/examples$ python3 tof_test.py
Traceback (most recent call last):
  File "tof_test.py", line 2, in <module>
    import ydlidar
  File "/home/elias/YDLidar-SDK/python/examples/ydlidar.py", line 15, in <module>
    import _ydlidar
ModuleNotFoundError: No module named '_ydlidar'
elias@elias-ThinkPad:~/YDLidar-SDK/python/examples$ python plot_tof_test.py
Traceback (most recent call last):
  File "plot_tof_test.py", line 2, in <module>
    import ydlidar
  File "/home/elias/YDLidar-SDK/python/examples/ydlidar.py", line 15, in <module>
    import _ydlidar
ImportError: dynamic module does not define init function (init_ydlidar)
elias@elias-ThinkPad:~/YDLidar-SDK/python/examples$ python3 plot_tof_test.py
Traceback (most recent call last):
  File "plot_tof_test.py", line 2, in <module>
    import ydlidar
  File "/home/elias/YDLidar-SDK/python/examples/ydlidar.py", line 15, in <module>
    import _ydlidar
ModuleNotFoundError: No module named '_ydlidar'

```

**Comment by JHPHELAN** [comment]
Same problem here.
